version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
        environment:
            - MONGO_URL=${MONGO_URL}

    db:
        image: mongo:latest
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
