const ERROR_MESSAGES = {
	BAD_REQUEST: "Bad request",
	NOT_FOUND: "Not found",
	ACCESS_DENIED: "Access denied",
	UN_AUTHORIZED: "Unauthorized",
	INTERNAL_SERVER_ERROR: "Internal server error",
	LOGIN_PASSWORD_REQUIRED: "Login and password are required",
	USER_NOT_FOUND: "User not found",
	USER_ALREADY_EXISTS: "User already exists",
	PASSWORD_MISMATCH: "Password and confirmation do not match",
	MISSING_REQUIRED_FIELDS: "One or more required fields are missing",
	INVALID_TOKEN: "Invalid token payload",
	LOGIN_OR_PASSWORD_REQUIRED: "Login or password are required",
	INVALID_LOGIN_OR_PASSWORD: "Invalid login or password",
	INVALID_ROLE: "Invalid role",
	DISH_NOT_FOUND: "Dish not found",
	ACCOUNT_ALREADY_EXISTS: "Account already exists",
	ACCOUNT_NOT_FOUND: "Account not found",
	ACCOUNT_NOT_CREATED: "Account not created",
	DISH_NOT_FOUND_IN_CART: "Dish not found in cart",
	RESTAURANT_NOT_FOUND: "Restaurant not found",
	MENU_NOT_CREATED: "Menu not created",
	MENU_NOT_FOUND: "Menu not found",
	MENU_ID_AND_DISH_ID_REQUIRED: "menu_id and dish_id are required",
	INVALID_LOGIN_DATA: "Invalid login data",
	INVALID_REGISTRATION_DATA: "Invalid registration data",
	DISH_NOT_FOUND_IN_RESTAURANT: "Dish not found in restaurant",
	INCORRECT_DATA: "Incorrect data",
	CART_NOT_FOUND: "Cart not found",
	ORDER_ALREADY_EXIST: "Order already exists",
	ORDER_NOT_EXIST: "Order not exist",
	ORDER_NOT_FOUND: "Order not found",
	ORDER_ALREADY_CANCELLED: "Order already cancelled",
	COURIER_NOT_FOUND: "Courier not found",
	CANNOT_SET_STATUS_TO_ACTIVE: "Cannot set status to active in order",
	CANNOT_SET_STATUS_TO_IS_PROCESSED:
		"Cannot set status to isProcessed in order",
	CANNOT_SET_STATUS_TO_DELIVERED: "Cannot set status to delivered in order",
	CANNOT_SET_STATUS_TO_COMPLETED: "Cannot set status to completed in order",
	CANNOT_SET_STATUS_TO_CANCELED: "Cannot set status to canceled in order",
	INVALID_ORDER_STATUS: "Invalid order status",
};

export default ERROR_MESSAGES;
